name: backend-tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.4
      - name: Install
        run: yarn install --frozen-lockfile --cwd ./backend
      - name: run tests
        run: |
          cd ./backend 
          yarn test
