name: nft-gallery

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  static-analysis:
    runs-on: ubuntu:latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.4
      - name: Install Dependencies
        run: | 
          yarn install --frozen-lockfile --cwd ./backend &&
          yarn install --frozen-lockfile --cwd ./frontend
      - name: Lint
        run: yarn --cwd ./backend lint && yarn --cwd ./frontend lint